spring:
  application:
    name: pixprodutor
  datasource:
    url: jdbc:postgresql://localhost:5432/aulakafka
    username: devuser
    password: dev1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8080